dist: xenial

language: ruby

#ruby version is specified in .ruby-version

addons:
  postgresql: "9.6"

before_script:
  - docker build . -t xanderflood/identify:local

script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo "staging" ; fi`

  - export DOCKER_REPO=xanderflood/identify
  - export tags="build-$TRAVIS_BUILD_NUMBER,commit-${TRAVIS_COMMIT::8},$TAG"
  - ./push_image.sh
